title: Wasif Jafri
logo: /assets/img/Wasif_headshot.png
theme: jekyll-theme-minimal
description: Portfolio of Wasif Jafri
show_downloads: true
markdown: kramdown

# Add custom CSS
include:
  - style.css
